# Generated by Django 3.1.3 on 2021-12-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('con_name', models.CharField(max_length=45)),
                ('con_detail', models.CharField(max_length=45)),
                ('con_text', models.TextField()),
            ],
            options={
                'db_table': 'context',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qu_id', models.AutoField(primary_key=True, serialize=False)),
                ('qu_name', models.CharField(max_length=45)),
                ('qu_detail', models.CharField(max_length=45)),
                ('qu_num', models.CharField(max_length=10)),
                ('qu_text', models.TextField()),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
    ]
